spring:
  jackson:
    default-property-inclusion: non_null
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        temp:
          use_jdbc_metadata_defaults : false
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:./h2/heroes;AUTO_SERVER=TRUE # this one is on the disk
    driverClassName: org.h2.Driver
    username: sa
    password: sa
    initialization-mode: always
    data: classpath:customers.sql
  h2:
    console:
      enabled: true
logging:
  file:
    path: ./logs
#    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1 # this one is in memory
#      this enables http://localhost:8080/h2-console
